### DISCUSSION TITLE
Is it possible to completely disable backup safety?

### DISCUSSION THREAD

**Discussion by siqiyan** [iRobotEducation/create3_docs#149] [Questions] [answered]
Hi, I am currently wrote a simple node that use the IR sensor to allow the Create 3 robot to follow its front obstacle but keep a fixed distance (around 10 cm). If the obstacle moves forward, the robot follows, and if the obstacle moves backward the robot backup accordingly. I am using a PID controller to generate continues motion command and send it to `cmd_vel` topic, right now the forward movement works perfectly, but the problem is that due to safety constraints the robot does not backup and the LED turns to yellow. I am aware that the robot has backup limit by default, so I went to the web interface and change `safety_override` to `full` and restart the application, but even doing this does not give me full backup control, everytime a negative linear motion is generated the robot LED still turns to yellow and it stops moving.
After some testing I found that if the negative motion (say linear.x=-0.5) is send only once the robot can backup for around half meter, then if the message is send again the robot will continue backup for another half meter and so on; but if the same motion command is send repeatedly at 10Hz then the robot will refuse to backup. So I think there is still some restrictions that prevent the robot from backup even if the `safety_override` is set to `full`. Is that possible to completely disable this constraint? Thanks!

**Comment by alsora** [comment]
This is not the expected behavior.
Setting `safety_override` to `full` should disable all safety mechanisms, as described in the [Safety Configuration docs](https://iroboteducation.github.io/create3_docs/api/safety/).

In particular, note that you can change safety settings using a ROS 2 parameter service call, rather than the webserver.
```
ros2 param set /motion_control safety_override full
```

Similarly, you can query the current safety value from a running robot using
```
ros2 param get /motion_control safety_override
```

Would you mind trying again using these calls and verifying that the parameter is set as expected?
It would also be helpful to see the logs on `/rosout` topic while you do these operations and then when you drive backward.

**Reply by siqiyan** [reply]
Hi, thanks for the reply! I tried to set the safety_override using the service call, and here is the output for the query:
```
String value is: full
```

Unfurtunately the robot still refuse to backup and the LED turns to yellow as before. Here is the output for `ros2 topic echo /rosout` when the robot stops:
```
stamp:
  sec: 1660427954
  nanosec: 349679318
level: 30
name: motion_control
msg: Reached backup limit! Stop Driving robot backward or disable from safety_override parameter!
file: ../../apps/create-platform/nodes/src/motion-control-node.cpp
function: control_robot
line: 294
```

**Reply by alsora** [reply]
Ok, thanks for the information.
Is your robot running the latest firmware version? This should be G.2.2, you can check the version from the webserver.

In any case, this seems to be a software bug.
I will run some test to investigate.

**Reply by siqiyan** [reply]
Yes, the firmware version is G.2.2

**Reply by eschembor-irobot** [reply]
Can you try setting the safety_override using the service call to "none" and then back to "full" and see if that allows the robot to move backwards.
Note that if the robot has already exhausted its backup budget before enabling the safety_override then you may still see the yellow LED and that "Reached backup limit!" message, although it should still allow the robot to backup.

**Reply by siqiyan** [reply]
> Can you try setting the safety_override using the service call to "none" and then back to "full" and see if that allows the robot to move backwards. Note that if the robot has already exhausted its backup budget before enabling the safety_override then you may still see the yellow LED and that "Reached backup limit!" message, although it should still allow the robot to backup.

Hi, I set the safety_override to "none" and then to "full" using the service call but it does not work, the LED still turns to yellow and the robot does not backup.

**Comment by maddiepero** [comment]
I have found success if I set the safety override parameter to full when I spin the node. Here is the link to an example code I wrote that does that. The specific function is set_params() and then I call that function as soon as I initialize the node in the main() function. https://github.com/tuftsceeo/Tufts_Create3_Examples/blob/main/Projects/Penalty_Shootout/penalty_kick.py

**Reply by siqiyan** [reply]
Hi, thanks for the reply! I followed your example code and set the safety_override parameter to 'full' in my Python script, but my robot still stuck when it supposed to backup using `cmd_vel`. However, I tried to use ActionClient and set a DriveDistance to -0.25 according to your code and the robot can backup normally. So I modify my script to make the robot first backup using ActionClient and then start to following obstacles using IR sensor, but the robot still stuck after finish executing the DriveDistance goal. Here is the `/rosout` output:
```
stamp:
  sec: 1660431077
  nanosec: 815497952
level: 20
name: motion_control
msg: Setting safety override to "full"
file: ../../apps/create-platform/nodes/src/motion-control-node.cpp
function: set_safety_mode
line: 470
---
stamp:
  sec: 1660431077
  nanosec: 847559056
level: 20
name: motion_control
msg: Received new drive_distance goal
file: ../../apps/create-platform/behaviors/include/create-platform/behaviors/drive-goal-behaviors.hpp
function: handle_drive_goal_goal
line: 98
---
stamp:
  sec: 1660431077
  nanosec: 848353737
level: 20
name: motion_control
msg: drive_distance goal with distance -0.250000, max_speed 0.306000
file: ../../apps/create-platform/behaviors/src/drive-goal-behaviors.cpp
function: initialize_goal
line: 218
---
stamp:
  sec: 1660431077
  nanosec: 849824937
level: 30
name: motion_control
msg: Reached backup limit! Stop Driving robot backward or disable from safety_override parameter!
file: ../../apps/create-platform/nodes/src/motion-control-node.cpp
function: control_robot
line: 294
---
stamp:
  sec: 1660431079
  nanosec: 609223972
level: 20
name: motion_control
msg: 'drive_distance goal succeeded: traveled commanded distance'
file: ../../apps/create-platform/behaviors/src/drive-goal-behaviors.cpp
function: iterate_on_goal
line: 236
---
stamp:
  sec: 1660431081
  nanosec: 149782830
level: 30
name: motion_control
msg: Reached backup limit! Stop Driving robot backward or disable from safety_override parameter!
file: ../../apps/create-platform/nodes/src/motion-control-node.cpp
function: control_robot
line: 294
---
```

It seems that the robot is able to backup with ActionClient even if it is complaining with reached backup limit, but it won't backup using the `cmd_vel` topic.
