### DISCUSSION TITLE
[TB4/Create3] /battery_state topic time stamp and data repeated 17 times?

### DISCUSSION THREAD

**Discussion by slowrunner** [iRobotEducation/create3_docs#243] [Questions] [answered]
My (TurtleBot4lite's) Create3 publishes a /battery_state topic roughly every 10 seconds, but the header time stamp and data only changes after 169 seconds.

Create3 Version G.3.1
ROS2 Galactic

Is this a defect, and if so where do I file the issue?

Simplified output from ```ros2 topic echo /battery_state```
```
---
header:
  stamp:
    sec: 1668885286
    nanosec: 307109232
  frame_id: ''
voltage: 14.880000114440918
temperature: 42.45000076293945
current: 0.42100000381469727
charge: 0.9739999771118164
capacity: 2.049999952316284
design_capacity: 2.049999952316284
percentage: 0.47999998927116394

---
header:
  stamp:
    sec: 1668885463              <<--- TimeStamp and Data Changed
    nanosec: 885139612
  frame_id: ''
voltage: 14.902000427246094
temperature: 42.54999923706055
current: 0.4269999861717224
charge: 0.9950000047683716
capacity: 2.049999952316284
design_capacity: 2.049999952316284
percentage: 0.49000000953674316


---
header:
  stamp:
    sec: 1668885463
    nanosec: 885139612
  frame_id: ''
voltage: 14.902000427246094
temperature: 42.54999923706055
current: 0.4269999861717224
charge: 0.9950000047683716
capacity: 2.049999952316284
design_capacity: 2.049999952316284
percentage: 0.49000000953674316


---
header:
  stamp:
    sec: 1668885463
    nanosec: 885139612
  frame_id: ''
voltage: 14.902000427246094
temperature: 42.54999923706055
current: 0.4269999861717224
charge: 0.9950000047683716
capacity: 2.049999952316284
design_capacity: 2.049999952316284
percentage: 0.49000000953674316


---
header:
  stamp:
    sec: 1668885463
    nanosec: 885139612
  frame_id: ''
voltage: 14.902000427246094
temperature: 42.54999923706055
current: 0.4269999861717224
charge: 0.9950000047683716
capacity: 2.049999952316284
design_capacity: 2.049999952316284
percentage: 0.49000000953674316


---
header:
  stamp:
    sec: 1668885463
    nanosec: 885139612
  frame_id: ''
voltage: 14.902000427246094
temperature: 42.54999923706055
current: 0.4269999861717224
charge: 0.9950000047683716
capacity: 2.049999952316284
design_capacity: 2.049999952316284
percentage: 0.49000000953674316


---
header:
  stamp:
    sec: 1668885463
    nanosec: 885139612
  frame_id: ''
voltage: 14.902000427246094
temperature: 42.54999923706055
current: 0.4269999861717224
charge: 0.9950000047683716
capacity: 2.049999952316284
design_capacity: 2.049999952316284
percentage: 0.49000000953674316


---
header:
  stamp:
    sec: 1668885463
    nanosec: 885139612
  frame_id: ''
voltage: 14.902000427246094
temperature: 42.54999923706055
current: 0.4269999861717224
charge: 0.9950000047683716
capacity: 2.049999952316284
design_capacity: 2.049999952316284
percentage: 0.49000000953674316


---
header:
  stamp:
    sec: 1668885463
    nanosec: 885139612
  frame_id: ''
voltage: 14.902000427246094
temperature: 42.54999923706055
current: 0.4269999861717224
charge: 0.9950000047683716
capacity: 2.049999952316284
design_capacity: 2.049999952316284
percentage: 0.49000000953674316


---
header:
  stamp:
    sec: 1668885463
    nanosec: 885139612
  frame_id: ''
voltage: 14.902000427246094
temperature: 42.54999923706055
current: 0.4269999861717224
charge: 0.9950000047683716
capacity: 2.049999952316284
design_capacity: 2.049999952316284
percentage: 0.49000000953674316


---
header:
  stamp:
    sec: 1668885463
    nanosec: 885139612
  frame_id: ''
voltage: 14.902000427246094
temperature: 42.54999923706055
current: 0.4269999861717224
charge: 0.9950000047683716
capacity: 2.049999952316284
design_capacity: 2.049999952316284
percentage: 0.49000000953674316


---
header:
  stamp:
    sec: 1668885463
    nanosec: 885139612
  frame_id: ''
voltage: 14.902000427246094
temperature: 42.54999923706055
current: 0.4269999861717224
charge: 0.9950000047683716
capacity: 2.049999952316284
design_capacity: 2.049999952316284
percentage: 0.49000000953674316


---
header:
  stamp:
    sec: 1668885463
    nanosec: 885139612
  frame_id: ''
voltage: 14.902000427246094
temperature: 42.54999923706055
current: 0.4269999861717224
charge: 0.9950000047683716
capacity: 2.049999952316284
design_capacity: 2.049999952316284
percentage: 0.49000000953674316


---
header:
  stamp:
    sec: 1668885463
    nanosec: 885139612
  frame_id: ''
voltage: 14.902000427246094
temperature: 42.54999923706055
current: 0.4269999861717224
charge: 0.9950000047683716
capacity: 2.049999952316284
design_capacity: 2.049999952316284
percentage: 0.49000000953674316


---
header:
  stamp:
    sec: 1668885463
    nanosec: 885139612
  frame_id: ''
voltage: 14.902000427246094
temperature: 42.54999923706055
current: 0.4269999861717224
charge: 0.9950000047683716
capacity: 2.049999952316284
design_capacity: 2.049999952316284
percentage: 0.49000000953674316


---
header:
  stamp:
    sec: 1668885463
    nanosec: 885139612
  frame_id: ''
voltage: 14.902000427246094
temperature: 42.54999923706055
current: 0.4269999861717224
charge: 0.9950000047683716
capacity: 2.049999952316284
design_capacity: 2.049999952316284
percentage: 0.49000000953674316

---
header:
  stamp:
    sec: 1668885463
    nanosec: 885139612
  frame_id: ''
voltage: 14.902000427246094
temperature: 42.54999923706055
current: 0.4269999861717224
charge: 0.9950000047683716
capacity: 2.049999952316284
design_capacity: 2.049999952316284
percentage: 0.49000000953674316

---
header:
  stamp:
    sec: 1668885463
    nanosec: 885139612
  frame_id: ''
voltage: 14.902000427246094
temperature: 42.54999923706055
current: 0.4269999861717224
charge: 0.9950000047683716
capacity: 2.049999952316284
design_capacity: 2.049999952316284
percentage: 0.49000000953674316

---
header:
  stamp:
    sec: 1668885632            <<-- TimeStamp and Data Changed
    nanosec: 998287917
  frame_id: ''
voltage: 14.92300033569336
temperature: 42.54999923706055
current: 0.4230000078678131
charge: 1.0149999856948853
capacity: 2.049999952316284
design_capacity: 2.049999952316284
percentage: 0.5
```
