### DISCUSSION TITLE
Option for wheel odometry only /odom topic

### DISCUSSION THREAD

**Discussion by jmm-slamcore** [iRobotEducation/create3_docs#311] [Ideas]
The `/odom` topic publishes odometry readings that are generated by fusing wheel odometry, imu and the optical mouse data. Even though the Create publishes the raw sensor readings on `/wheel_status`, `/wheel_ticks`, `/wheel_vels` so users can implement their own algorithms, have you considered adding a toggle/parameter flag that would allow users to choose between a fused odometry and wheel odometry only `/odom` topic? 

This would be for e.g. situations where users want to fuse the wheel odometry data with other sensors themselves but without having to write their own node that subscribes to `/wheel_ticks` and publishes an `/odom` message. Not a super high priority request but a suggestion.

**Comment by alsora** [comment]
Hi  @jmm-slamcore,
this is currently not available, but it should be simple to add in one of the next software releases.
We will let you know once it's available and how to control it

**Comment by jmm-slamcore** [comment]
This would also be useful as it seems that the `/odom` topic still publishes some changing values (albeit very small) for Twist when the robot is completely static, I imagine because of the IMU:
```
ros2 topic echo /odom --field twist.twist
```

```
linear:
  x: 0.0
  y: 0.0
  z: 0.0
angular:
  x: 2.1088288448822823e-08
  y: 9.037838255565589e-10
  z: 2.3136865934247908e-07
---
linear:
  x: 0.0
  y: 0.0
  z: 0.0
angular:
  x: 1.24372501186798e-09
  y: 2.1765187430133892e-09
  z: 2.387951951732248e-07
---
linear:
  x: 0.0
  y: 0.0
  z: 0.0
angular:
  x: -1.7950037900504867e-08
  y: 3.5900076245098944e-09
```
