### DISCUSSION TITLE
What Virtual Wall Works For Create3?

### DISCUSSION THREAD

**Discussion by slowrunner** [iRobotEducation/create3_docs#517] [Questions] [answered]
### How are you connecting to your Create 3?

Wi-Fi (ROS 2)

### Computer(s) Model(s) and Operating System(s)

Ubuntu 22.04 in Docker over Raspberry Pi 5 PiOS Bookworm

### Which version of ROS 2 is installed on your computer?

Humble

### Which firmware version is installed on your robot?

H.2.4

### Which RMW is your robot running?

I don't know

### Is the robot connected to a network? If so, what is the network type?

Yes: 2.4GHz Home WiFi 

### Are there multiple Create 3 robots connected to your network?

No

### Is multicast enabled?

Yes

### What is the Adapter Board's USB/BLE Toggle currently switched to?

Bluetooth (default)

### Describe your question.

Which model(s) of iRobot Virtual Wall is(are) compatible with the Create3?

Any tips on programming with the virtual wall?

Works for the moment:
![Cardboard_Wall](https://github.com/iRobotEducation/create3_docs/assets/8950202/b1068ea0-98c5-4c19-9676-854eb5748625)

**Comment by shamlian** [comment, marked as answer]
If you're tired of using an Actual Wall™, you can use [this Virtual Wall®](https://www.irobot.com/en_US/dual-mode-virtual-wall-barrier/4636429.html), which will appear as opcode `162` in the `/ir_opcode` topic.

**Reply by slowrunner** [reply]
So cool - It's so tiny - didn't expect that from the pictures.

```
pi@WaLiPi5:~/wali_pi5/c3ws $ ros2 topic echo --once /ir_opcode
header:
  stamp:
    sec: 1706299204
    nanosec: 891169655
  frame_id: ir_omni
opcode: 162
sensor: 0
---
pi@WaLiPi5:~/wali_pi5/c3ws $ 
```

![Virtual Wall For Wali](https://github.com/iRobotEducation/create3_docs/assets/8950202/52b05c39-8d66-4211-8aa1-374afa92785e)

Have to add virtual wall to my wander program and finally get rid of the cardboard wall.
