### DISCUSSION TITLE
Log from Create3 Seizures supporting RTABmap and rviz2

### DISCUSSION THREAD

**Discussion by slowrunner** [iRobotEducation/create3_docs#563] [Questions]
### How are you connecting to your Create 3?

Wi-Fi and USB Ethernet (ROS 2)

### Computer(s) Model(s) and Operating System(s)

Ubuntu 22.04 in Docker over Raspberry Pi 5 PiOS Bookworm

### Which version of ROS 2 is installed on your computer?

Humble

### Which firmware version is installed on your robot?

(Latest Humble) H2.6

### Which RMW is your robot running?

FastRTPS

### Is the robot connected to a network? If so, what is the network type?

Yes: 2.4GHz Home WiFi (used for ntp - not using chrony for ntp)

### Are there multiple Create 3 robots connected to your network?

No

### Is multicast enabled?

Yes

### What is the Adapter Board's USB/BLE Toggle currently switched to?

USB

### Describe your question.

# Create3 log file from cold boot through two runs of RTABmap and rviz2

(Not looking for answers - just documenting the problem)

Create3 seized up periodically, eventually honoring some /cmd_vel topics for a short while, then would seize up again.

It survived and seemed to return to normal function when RTABmap and rviz2 exited:
- was able to drive Create3 back to dock area (after RTABmap and rviz2 exited)
- successfully /rotate_angle 180 to face dock
- successfully accomplished /dock
- CPU returned to   

Using the following Create3 app config 
```
motion_control:
  ros__parameters:
    # safety_override options are 
    # "none" - standard safety profile, robot cannot backup more than an inch because of lack of cliff protection in rear, max speed 0.306m/s
    # "backup_only" - allow backup without cliff safety, but keep cliff safety forward and max speed at 0.306m/s
    # "full" - no cliff safety, robot will ignore cliffs and set max speed to 0.46m/s
    safety_override: "full"

robot_state:
  ros__parameters:
    # publish_hazard_msgs: default true, set false to noticeably reduce CPU and RAM useage
    publish_hazard_msgs: false
    # publish_odom_tfs: default true, if not needed will noticeably reduce CPU and RAM use
    publish_odom_tfs: false 
    # raw_kinematics_min_pub_period_ms: default 25 , -1 disables /imu, /mouse, /wheel_status, /wheel_ticks, /wheel_vels (-1 recommended)
    raw_kinematics_min_pub_period_ms: -1
    # hazards_pub_fixed_period_ms: default -1 disables fixed period hazard publication, pubs only when change noted, 1: publish as soon as possible, 2+ period for constant publishing 
```

(Started rviz2 one to three minutes after starting RTABmap)

Started RTABmap at:   Saturday 03/02/24 20:56:13 EST  01:56:13 UTC
Stopped RTABmap at: Saturday 03/02/24 21:09:20 EST  02:09:20 UTC

Re-Started RTABmap at:   Saturday 03/02/24 21:10:03 EST  02:10:03 UTC
Stopped RTABmap at:       Saturday 03/02/24 21:24:40 EST  02:24:40 UTC

Create3 has FastDDS Discover Server enabled with 192.168.186.3:11811
Raspberry Pi5 has usb0 mapped to 192.168.186.3 with Discovery server 0 running
Raspberry Pi5 uptime reported load around 2.0

```
pi@WaLiPi5:~/wali_pi5/c3ws $ docker logs r2hdp
START_WALI.SH EXECUTING
*** fastdds discovery -i 0 -l 192.168.186.3 -p 11811 -l 10.0.0.219 -p 11811 -l 127.0.0.1 -p 11811 &
### Server is running ###
  Participant Type:   SERVER
  Security:           NO
  Server ID:          0
  Server GUID prefix: 44.53.00.5f.45.50.52.4f.53.49.4d.41
  Server Addresses:   UDPv4:[192.168.186.3]:11811
                      UDPv4:[10.0.0.219]:11811
                      UDPv4:[127.0.0.1]:11811

*** Start F710 game controller node
*** ros2 launch teleop_twist_joy teleop-launch.py joy_config:="F710" 

*** Start odometer node
*** ros2 run wali odometer & 

*** Start wali.say_node
*** ros2 run wali say_node &
[INFO] [launch]: All log files can be found below /home/pi/.ros/log/2024-03-02-20-31-27-309296-WaLiPi5-74
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [joy_node-1]: process started with pid [111]
[INFO] [teleop_node-2]: process started with pid [113]
** WaLI node started - Undock:99% Rotate:18% Dock:15% **
[teleop_node-2] [INFO] [1709429488.350749289] [TeleopTwistJoy]: Teleop enable button 4.
[teleop_node-2] [INFO] [1709429488.350816234] [TeleopTwistJoy]: Turbo on button 5.
[teleop_node-2] [INFO] [1709429488.350821567] [TeleopTwistJoy]: Linear axis x on 1 at scale 0.150000.
[teleop_node-2] [INFO] [1709429488.350830734] [TeleopTwistJoy]: Turbo for linear axis x is scale 0.300000.
[teleop_node-2] [INFO] [1709429488.350835826] [TeleopTwistJoy]: Angular axis yaw on 0 at scale 0.250000.
[teleop_node-2] [INFO] [1709429488.350840141] [TeleopTwistJoy]: Turbo for angular axis yaw is scale 0.500000.
[joy_node-1] [INFO] [1709429488.969516336] [joy_node]: Opened joystick: Logitech Gamepad F710.  deadzone: 0.300000
[INFO] [1709432669.096050691] [wali_node]: rotate Goal Accepted :)
[INFO] [1709432728.846013063] [wali_node]: rotate Goal Accepted :)
[INFO] [1709432968.892500090] [wali_node]: dock Goal Accepted

```
[RTABmapLog.txt](https://github.com/iRobotEducation/create3_docs/files/14471525/RTABmapLog.txt)
