### DISCUSSION TITLE
Wait for service timed out when trying to set parameters (firmware H.2.6)

### DISCUSSION THREAD

**Discussion by xiaoshan-lin** [iRobotEducation/create3_docs#565] [Questions]
Hello,

After upgrading to **firmware H.2.6**, we try to set  parameters **publish_hazard_msgs**, **raw_kinematics_min_pub_period_ms** and **publish_odom_tfs** to reduce CPU and RAM usage. 

However, we got a "**Wait for service timed out**" message when we call ros2 param load /turtlebot1/robot_state param.yaml and ros2 param load /turtlebot2/robot_state param.yaml. The param.yaml file is attached below.

Do you know how to solve this problem? Thanks in advance for your help and support.

```
/turtlebot1/robot_state:
  ros__parameters:
    publish_hazard_msgs: false
    publish_odom_tfs: false
    raw_kinematics_min_pub_period_ms: -1
    
/turtlebot2/robot_state:
  ros__parameters:
    publish_hazard_msgs: false
    publish_odom_tfs: false
    raw_kinematics_min_pub_period_ms: -1

```
