### DISCUSSION TITLE
I have  NAV2 working with Create 3 :)    I cheated a little... Used TurtleBot4 code and merged it with what was working properly with the Create3 Base!

### DISCUSSION THREAD

**Discussion by jerrynsr** [iRobotEducation/create3_docs#68] [Questions] [answered]
I'm using the sensors_launch.py from the Create3 examples, Create3 Gazebo examples,  and modified code from the TurtleBot4 github.  I successfully mapped my house and was able to send the robot on NAV2 missions!   I'll post a video soon.   It's pretty cool watching to bot navigate through the rooms and hallways.    I dispatched the robot from my hobby room to my living room,  out to the kitchen,  out to the den.. all through Rviz 2 Nav2.    Is there a way to increase the distance between the Create3 base and obstacles in the way ?   Some objects fool LIDAR.. such as a large fan with a pedestal base,   Will adding an Oak D lite camera and depthai ros2 code help navigating around object like that ?

**Comment by justinIRBT** [comment, marked as answer]
In the Nav2 stacks costmap parameters, there are fields:
```
local_costmap:
  local_costmap:
    ros__parameters:
      resolution: 0.05
      robot_radius: 0.175
      footprint_padding: 0.03
```
Increasing those values will increase offset from obstacles, but you have to be careful, as if you grow obstacles too much, you won't be able to get through tighter spaces.

The 3D data from the Oak D lite would help to see things outside of the laser plane.  For example, if your fan's base is tall enough for the robot to distinguish it from the floor, but below the laser plane, the robot may see it as an obstacle with the 3D sensor.  You will have to fool around with the voxel layer z values to get the height at which things are considered obstacles, see the `origin_z` through `max_obstacle_height` fields below
```
local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 5.0
      publish_frequency: 2.0
      global_frame: odom
      robot_base_frame: base_link
      use_sime_time: False
      rolling_window: true
      width: 3
      height: 3
      resolution: 0.05
      robot_radius: 0.175
      footprint_padding: 0.03
      plugins: ["obstacle_layer", "voxel_layer", "inflation_layer"]
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 3.0
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        observation_sources: scan
        scan:
          topic: /scan
          clearing: True
          marking: True
          data_type: "LaserScan"
      voxel_layer:
        plugin: "nav2_costmap_2d::VoxelLayer"
        enabled: True
        publish_voxel_map: True
        origin_z: -0.02
        z_resolution: 0.05
        z_voxels: 6
        max_obstacle_height: 0.28
        mark_threshold: 1
        observation_sources: pointcloud
        pointcloud:
          topic: /pointcloud
          max_obstacle_height: 0.5
          clearing: True
          marking: True
          data_type: "PointCloud2"
      static_layer:
        map_subscribe_transient_local: True
      always_send_full_costmap: True
  local_costmap_client:
    ros__parameters:
      use_sime_time: False
  local_costmap_rclcpp_node:
    ros__parameters:
      use_sime_time: False
```
